/**
 * The original 136 free-text ingredient lines, exactly as they were written
 * before the §4.1 migration restructured them into `Ingredient`.
 *
 * Frozen here on purpose. The parser's job is to read lines like these, so the
 * corpus spec has to keep testing the messy originals — it cannot read the
 * migrated data, which is already clean by construction.
 */
export const INGREDIENT_CORPUS: ReadonlyArray<{ recipe: string; line: string }> = [
  // grandmas-spaghetti
  { recipe: 'grandmas-spaghetti', line: '1/2 hamburger' },
  { recipe: 'grandmas-spaghetti', line: '2 tablespoons dried onion' },
  { recipe: 'grandmas-spaghetti', line: '1 small can tomato paste' },
  { recipe: 'grandmas-spaghetti', line: 'can of tomato juice' },
  { recipe: 'grandmas-spaghetti', line: '1 tablespoon garlic powder' },
  { recipe: 'grandmas-spaghetti', line: ' 1 tablespoon chili powder' },
  { recipe: 'grandmas-spaghetti', line: '1 teaspoon sugar' },
  // grandmas-chili
  { recipe: 'grandmas-chili', line: '1 pound hamburger' },
  { recipe: 'grandmas-chili', line: '1 can kidney beans' },
  { recipe: 'grandmas-chili', line: '2 can chili beans' },
  { recipe: 'grandmas-chili', line: '1 can vegetable juice' },
  { recipe: 'grandmas-chili', line: 'Chili powder to taste' },
  { recipe: 'grandmas-chili', line: '1 teaspoon sugar' },
  { recipe: 'grandmas-chili', line: 'Salt to taste' },
  { recipe: 'grandmas-chili', line: 'Can of diced tomatoes (optional)' },
  // spicy-shrimp-pasta-in-tomato-cream-sauce
  { recipe: 'spicy-shrimp-pasta-in-tomato-cream-sauce', line: '14 oz rigatoni' },
  { recipe: 'spicy-shrimp-pasta-in-tomato-cream-sauce', line: '1 pound shrimp' },
  { recipe: 'spicy-shrimp-pasta-in-tomato-cream-sauce', line: '4 garlic cloves, minced' },
  { recipe: 'spicy-shrimp-pasta-in-tomato-cream-sauce', line: '1 shallot, finely chopped' },
  { recipe: 'spicy-shrimp-pasta-in-tomato-cream-sauce', line: '1 can (400 ml/14 oz) crushed tomatoes' },
  { recipe: 'spicy-shrimp-pasta-in-tomato-cream-sauce', line: '3/4 cup/200 ml low fat cream' },
  { recipe: 'spicy-shrimp-pasta-in-tomato-cream-sauce', line: '4.5 oz semi sun-dried tomatoes, drained' },
  { recipe: 'spicy-shrimp-pasta-in-tomato-cream-sauce', line: '1/2 cup dry white wine' },
  { recipe: 'spicy-shrimp-pasta-in-tomato-cream-sauce', line: 'oil, drained from sun-dried tomatoes jar' },
  { recipe: 'spicy-shrimp-pasta-in-tomato-cream-sauce', line: '1 tsp chili flakes, more to taste' },
  { recipe: 'spicy-shrimp-pasta-in-tomato-cream-sauce', line: '1/2 tsp each: dried oregano, thyme, smoked paprika' },
  { recipe: 'spicy-shrimp-pasta-in-tomato-cream-sauce', line: '1 tsp fish sauce' },
  { recipe: 'spicy-shrimp-pasta-in-tomato-cream-sauce', line: 'crumbled feta, for serving' },
  { recipe: 'spicy-shrimp-pasta-in-tomato-cream-sauce', line: 'salt + black pepper' },
  // marry-me-chicken
  { recipe: 'marry-me-chicken', line: '1 lb chicken thighs' },
  { recipe: 'marry-me-chicken', line: '¼ teaspoon ground black pepper' },
  { recipe: 'marry-me-chicken', line: '6 tablespoons all-purpose flour' },
  { recipe: 'marry-me-chicken', line: '2 tablespoons olive oil' },
  { recipe: 'marry-me-chicken', line: '2 tablespoons butter' },
  { recipe: 'marry-me-chicken', line: '3 cloves garlic minced' },
  { recipe: 'marry-me-chicken', line: '1 cup chicken stock' },
  { recipe: 'marry-me-chicken', line: '1 cup heavy cream' },
  { recipe: 'marry-me-chicken', line: '½ cup parmesan cheese grated' },
  { recipe: 'marry-me-chicken', line: '1 teaspoon chili flakes' },
  { recipe: 'marry-me-chicken', line: '¼ teaspoon oregano' },
  { recipe: 'marry-me-chicken', line: '¼ teaspoon thyme' },
  { recipe: 'marry-me-chicken', line: '⅓ cup sundried tomatoes chopped' },
  { recipe: 'marry-me-chicken', line: '1 tablespoon fresh basil leaves' },
  // honey-buffalo-sauce
  { recipe: 'honey-buffalo-sauce', line: '1/2 cup honey' },
  { recipe: 'honey-buffalo-sauce', line: '1 cup buffalo wing sauce' },
  { recipe: 'honey-buffalo-sauce', line: '1/4 cup packed brown sugar' },
  { recipe: 'honey-buffalo-sauce', line: '2 tbsp orange marmalade' },
  { recipe: 'honey-buffalo-sauce', line: '2 tbsp apricot spreadable fruit' },
  { recipe: 'honey-buffalo-sauce', line: '2 tablespoons soy sauce' },
  { recipe: 'honey-buffalo-sauce', line: '1/4 teaspoon crushed red pepper flakes' },
  // mango-chutney-chicken-sheet-pan
  { recipe: 'mango-chutney-chicken-sheet-pan', line: '8 Boneless, skinless, chicken thighs, about 2 lbs' },
  { recipe: 'mango-chutney-chicken-sheet-pan', line: '1 (9 oz) jar Mango chutney' },
  { recipe: 'mango-chutney-chicken-sheet-pan', line: '1 Head of cauliflower, cut into florets' },
  { recipe: 'mango-chutney-chicken-sheet-pan', line: '3 tbsp Olive oil' },
  { recipe: 'mango-chutney-chicken-sheet-pan', line: '2 tsp Salt' },
  { recipe: 'mango-chutney-chicken-sheet-pan', line: 'Cilantro, chopped, optional' },
  { recipe: 'mango-chutney-chicken-sheet-pan', line: 'Red onion, thinly sliced, optional' },
  { recipe: 'mango-chutney-chicken-sheet-pan', line: 'Cooked rice, quinoa or couscous for serving' },
  // sesame-garlic-ramen-noodles
  { recipe: 'sesame-garlic-ramen-noodles', line: '3 (3 oz) packages Instant ramen noodles, flavor packets discarded' },
  { recipe: 'sesame-garlic-ramen-noodles', line: '1⁄4 cup Low sodium soy sauce' },
  { recipe: 'sesame-garlic-ramen-noodles', line: '1⁄4 cup Oyster sauce or hoisin sauce if vegetarian' },
  { recipe: 'sesame-garlic-ramen-noodles', line: '1 tbsp Rice vinegar' },
  { recipe: 'sesame-garlic-ramen-noodles', line: '1 tbsp Brown sugar, optional' },
  { recipe: 'sesame-garlic-ramen-noodles', line: '1⁄2 -1 tsp Chili sauce like sambal or sriracha' },
  { recipe: 'sesame-garlic-ramen-noodles', line: '1⁄4cup Water' },
  { recipe: 'sesame-garlic-ramen-noodles', line: '2 tbsp Toasted sesame oil' },
  { recipe: 'sesame-garlic-ramen-noodles', line: '4 Cloves garlic, minced about 2 tsp' },
  { recipe: 'sesame-garlic-ramen-noodles', line: '1 tsp Freshly grated ginger' },
  { recipe: 'sesame-garlic-ramen-noodles', line: '4-6 Green onions, thinly sliced' },
  { recipe: 'sesame-garlic-ramen-noodles', line: '1 tsp Sesame seeds' },
  // baked-chicken-parmesan
  { recipe: 'baked-chicken-parmesan', line: '4 large boneless skinless chicken breasts' },
  { recipe: 'baked-chicken-parmesan', line: '1 egg' },
  { recipe: 'baked-chicken-parmesan', line: '1/2 cup panko breadcrumbs' },
  { recipe: 'baked-chicken-parmesan', line: '1/2 grated parmesan cheese' },
  { recipe: 'baked-chicken-parmesan', line: '1 teaspoon salt' },
  { recipe: 'baked-chicken-parmesan', line: '1 teaspoon pepper' },
  { recipe: 'baked-chicken-parmesan', line: '1 teaspoon garlic powder' },
  { recipe: 'baked-chicken-parmesan', line: '1 cup marinara sauce' },
  { recipe: 'baked-chicken-parmesan', line: '1 cup shredded mozzarella cheese' },
  { recipe: 'baked-chicken-parmesan', line: '1/4 cup fresh basil finely chopped' },
  { recipe: 'baked-chicken-parmesan', line: '1 bag Green Giant Roasted Broccoli or any frozen broccoli' },
  // stuffed-bell-peppers
  { recipe: 'stuffed-bell-peppers', line: '6 bell peppers, any color' },
  { recipe: 'stuffed-bell-peppers', line: '4 tablespoons olive oil, plus more for drizzling' },
  { recipe: 'stuffed-bell-peppers', line: '8 ounces lean ground beef' },
  { recipe: 'stuffed-bell-peppers', line: 'Kosher salt and freshly ground black pepper' },
  { recipe: 'stuffed-bell-peppers', line: '1 onion, finely diced' },
  { recipe: 'stuffed-bell-peppers', line: '2 cloves garlic, chopped' },
  { recipe: 'stuffed-bell-peppers', line: '1 medium zucchini, finely diced' },
  { recipe: 'stuffed-bell-peppers', line: '4 Roma tomatoes, seeded and finely diced' },
  { recipe: 'stuffed-bell-peppers', line: 'Red pepper flakes, as needed' },
  { recipe: 'stuffed-bell-peppers', line: '1 cup cooked long-grain and wild rice' },
  { recipe: 'stuffed-bell-peppers', line: '1 1/2 cups grated pepper Jack cheese' },
  // vanilla-crème-brûlée
  { recipe: 'vanilla-crème-brûlée', line: '2 cups heavy or light cream, or half-and-half' },
  { recipe: 'vanilla-crème-brûlée', line: '1 vanilla bean, split lengthwise, or 1 teaspoon vanilla extract' },
  { recipe: 'vanilla-crème-brûlée', line: '⅛ teaspoon salt' },
  { recipe: 'vanilla-crème-brûlée', line: '⅛ teaspoon salt' },
  { recipe: 'vanilla-crème-brûlée', line: '½ cup sugar, more for topping' },
  // homemade-mozzarella-sticks
  { recipe: 'homemade-mozzarella-sticks', line: '3/4 cup All purpose flour' },
  { recipe: 'homemade-mozzarella-sticks', line: '2 tsp Sea salt' },
  { recipe: 'homemade-mozzarella-sticks', line: '1/2 tsp Black pepper' },
  { recipe: 'homemade-mozzarella-sticks', line: '1 tsp Garlic powder' },
  { recipe: 'homemade-mozzarella-sticks', line: '2 Eggs' },
  { recipe: 'homemade-mozzarella-sticks', line: '2 cups Panko' },
  { recipe: 'homemade-mozzarella-sticks', line: '2 tsp Italian seasoning' },
  { recipe: 'homemade-mozzarella-sticks', line: '12 oz Low moisture mozzarella cheese cut into pieces 3-inch x ¾ inch, or 12 oz string cheese cut in half' },
  { recipe: 'homemade-mozzarella-sticks', line: '1 jar marinara sauce' },
  // sausage-breakfast-casserole
  { recipe: 'sausage-breakfast-casserole', line: '1 lb Breakfast sausage, raw ground (buy the maple kind if you want a hint of sweetness)' },
  { recipe: 'sausage-breakfast-casserole', line: '12 Eggs' },
  { recipe: 'sausage-breakfast-casserole', line: '1 tsp Salt' },
  { recipe: 'sausage-breakfast-casserole', line: '½ tsp Pepper' },
  { recipe: 'sausage-breakfast-casserole', line: '½ tsp Cayenne' },
  { recipe: 'sausage-breakfast-casserole', line: '1 cup Whipping cream' },
  { recipe: 'sausage-breakfast-casserole', line: '16 oz Cheddar cheese, shredded, divided' },
  { recipe: 'sausage-breakfast-casserole', line: '1 bunch Green onions, optional (about ½ cup)' },
  { recipe: 'sausage-breakfast-casserole', line: '1 lb Hash browns, thawed' },
  { recipe: 'sausage-breakfast-casserole', line: '2 tbsp Butter, melted' },
  // red-chicken-enchiladas
  { recipe: 'red-chicken-enchiladas', line: '4 cups cooked, shredded chicken' },
  { recipe: 'red-chicken-enchiladas', line: '3 cups Shredded mozzarella, (12 oz)' },
  { recipe: 'red-chicken-enchiladas', line: '3 cups Shredded monterey jack cheese, (12 oz)' },
  { recipe: 'red-chicken-enchiladas', line: '1 cup Sour cream' },
  { recipe: 'red-chicken-enchiladas', line: '2 Tbsp Taco Seasoning' },
  { recipe: 'red-chicken-enchiladas', line: '10 10” corn tortillas' },
  { recipe: 'red-chicken-enchiladas', line: '1 (28 oz) can Mild red enchilada sauce' },
  // chicken-taco-baked-sweet-potatoes
  { recipe: 'chicken-taco-baked-sweet-potatoes', line: '3 boneless, skinless chicken breast halves' },
  { recipe: 'chicken-taco-baked-sweet-potatoes', line: '8 oz can tomato sauce' },
  { recipe: 'chicken-taco-baked-sweet-potatoes', line: '1/2 cup salsa' },
  { recipe: 'chicken-taco-baked-sweet-potatoes', line: '2 teaspoons taco seasoning' },
  { recipe: 'chicken-taco-baked-sweet-potatoes', line: 'Salt and pepper to taste as desired' },
  { recipe: 'chicken-taco-baked-sweet-potatoes', line: '4 sweet potatoes' },
  { recipe: 'chicken-taco-baked-sweet-potatoes', line: '1/2 to 1 teaspoon chili powder' },
  { recipe: 'chicken-taco-baked-sweet-potatoes', line: '1/2 to 1 teaspoon MCT oil (optional)' },
  { recipe: 'chicken-taco-baked-sweet-potatoes', line: 'Fresh, snipped chives' },
  { recipe: 'chicken-taco-baked-sweet-potatoes', line: 'Fresh cilantro' },
  { recipe: 'chicken-taco-baked-sweet-potatoes', line: '0% Greek yogurt or sour cream' },
  { recipe: 'chicken-taco-baked-sweet-potatoes', line: 'Salsa' },
  { recipe: 'chicken-taco-baked-sweet-potatoes', line: 'Hot sauce' },
];
